sudo: required

language: node_js
node_js:
  - "0.12"

services:
  - docker

before_install:
  - npm install -g gulp
  - npm install -g bower

install:
  - npm install
  - bower install

script:
  - gulp
  - docker build -t hypheed/hypheed-webstub .
